// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bgQ3XimE2CDPtV2LtGEQc1p-Cw7CNdg',
    appId: '1:33271536677:web:d3a5270f32c1d4e9c633cc',
    messagingSenderId: '33271536677',
    projectId: 'inclass16-ccc62',
    authDomain: 'inclass16-ccc62.firebaseapp.com',
    storageBucket: 'inclass16-ccc62.firebasestorage.app',
    measurementId: 'G-D2M736QKSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeQZLJAMNcCn6sffPnCEegz3IXhBsHCk',
    appId: '1:33271536677:android:22c56ae4e1945233c633cc',
    messagingSenderId: '33271536677',
    projectId: 'inclass16-ccc62',
    storageBucket: 'inclass16-ccc62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3jz05X8UEVsoZQTNoivnHbPRVwed0u3g',
    appId: '1:33271536677:ios:b5196245e5d5dbbac633cc',
    messagingSenderId: '33271536677',
    projectId: 'inclass16-ccc62',
    storageBucket: 'inclass16-ccc62.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3jz05X8UEVsoZQTNoivnHbPRVwed0u3g',
    appId: '1:33271536677:ios:b5196245e5d5dbbac633cc',
    messagingSenderId: '33271536677',
    projectId: 'inclass16-ccc62',
    storageBucket: 'inclass16-ccc62.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_bgQ3XimE2CDPtV2LtGEQc1p-Cw7CNdg',
    appId: '1:33271536677:web:f3da63b9c2d2636fc633cc',
    messagingSenderId: '33271536677',
    projectId: 'inclass16-ccc62',
    authDomain: 'inclass16-ccc62.firebaseapp.com',
    storageBucket: 'inclass16-ccc62.firebasestorage.app',
    measurementId: 'G-KL0JH41D6X',
  );
}
